name: CI
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        release: [release-safe=false, release-safe=true, release-fast=true, release-small=true]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: goto-bus-stop/setup-zig@v2.0.1
        with:
          version: master
      - run: ./test.sh -D${{ matrix.release }}
